server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /var/www/html/public;
    index index.php;
    client_max_body_size 10m;
    resolver 127.0.0.11 ipv6=off valid=30s;

    location ^~ /storage/ {
        alias /var/www/html/storage/app/public/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        set $fpm_upstream app:9000;
        fastcgi_pass $fpm_upstream;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param HTTP_PROXY "";
        fastcgi_param HTTP_X_REAL_IP $http_x_real_ip;
        fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
        fastcgi_param HTTP_X_FORWARDED_PORT $http_x_forwarded_port;
        fastcgi_param HTTPS $http_x_forwarded_proto;
        fastcgi_read_timeout 120s;
    }

    location ~ /\. {
        deny all;
    }
}
